server:
  port: 8091

springdoc:
  api-docs:
    path: /payment-service/api-docs
  swagger-ui:
    path: /payment-service/swagger-api.html

application:
  temporal:
    server: "127.0.0.1:7233"
    namespace: "test-namespace"
    workers:
      PAYMENT:
        queue-name: "PAYMENT-SERVICE-QUEUE"
